In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('MovieLense.csv')
df

,Toy Story (1995),GoldenEye (1995),Four Rooms (1995),Get Shorty (1995),Copycat (1995),Shanghai Triad (Yao a yao yao dao waipo qiao) (1995),Twelve Monkeys (1995),Babe (1995),Dead Man Walking (1995),Richard III (1995),...,Kika (1993),Mirage (1995),Mamma Roma (1962),"Sunchaser, The (1996)","War at Home, The (1996)",Sweet Nothing (1995),Mat' i syn (1997),B. Monkey (1998),You So Crazy (1994),Scream of Stone (Schrei aus Stein) (1991)
0,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
939,NaN,NaN,NaN,2.0,NaN,NaN,4.0,5.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,5.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### User based CF

In [3]:
#결측치를 각 유저가 준 평균 점수로 채우기
df = df.apply(lambda x: x.fillna(x.mean()),axis=1)
df

,Toy Story (1995),GoldenEye (1995),Four Rooms (1995),Get Shorty (1995),Copycat (1995),Shanghai Triad (Yao a yao yao dao waipo qiao) (1995),Twelve Monkeys (1995),Babe (1995),Dead Man Walking (1995),Richard III (1995),...,Kika (1993),Mirage (1995),Mamma Roma (1962),"Sunchaser, The (1996)","War at Home, The (1996)",Sweet Nothing (1995),Mat' i syn (1997),B. Monkey (1998),You So Crazy (1994),Scream of Stone (Schrei aus Stein) (1991)
0,5.000000,3.000000,4.000000,3.000000,3.000000,5.000000,4.000000,1.000000,5.000000,3.000000,...,3.605166,3.605166,3.605166,3.605166,3.605166,3.605166,3.605166,3.605166,3.605166,3.605166
1,4.000000,3.704918,3.704918,3.704918,3.704918,3.704918,3.704918,3.704918,3.704918,2.000000,...,3.704918,3.704918,3.704918,3.704918,3.704918,3.704918,3.704918,3.704918,3.704918,3.704918
2,2.764706,2.764706,2.764706,2.764706,2.764706,2.764706,2.764706,2.764706,2.764706,2.764706,...,2.764706,2.764706,2.764706,2.764706,2.764706,2.764706,2.764706,2.764706,2.764706,2.764706
3,4.304348,4.304348,4.304348,4.304348,4.304348,4.304348,4.304348,4.304348,4.304348,4.304348,...,4.304348,4.304348,4.304348,4.304348,4.304348,4.304348,4.304348,4.304348,4.304348,4.304348
4,4.000000,3.000000,2.874286,2.874286,2.874286,2.874286,2.874286,2.874286,2.874286,2.874286,...,2.874286,2.874286,2.874286,2.874286,2.874286,2.874286,2.874286,2.874286,2.874286,2.874286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,4.312500,4.312500,4.312500,4.312500,4.312500,4.312500,4.312500,4.312500,5.000000,4.312500,...,4.312500,4.312500,4.312500,4.312500,4.312500,4.312500,4.312500,4.312500,4.312500,4.312500
939,3.457944,3.457944,3.457944,2.000000,3.457944,3.457944,4.000000,5.000000,3.000000,3.457944,...,3.457944,3.457944,3.457944,3.457944,3.457944,3.457944,3.457944,3.457944,3.457944,3.457944
940,5.000000,4.045455,4.045455,4.045455,4.045455,4.045455,4.000000,4.045455,4.045455,4.045455,...,4.045455,4.045455,4.045455,4.045455,4.045455,4.045455,4.045455,4.045455,4.045455,4.045455
941,4.259740,4.259740,4.259740,4.259740,4.259740,4.259740,4.259740,4.259740,4.259740,4.259740,...,4.259740,4.259740,4.259740,4.259740,4.259740,4.259740,4.259740,4.259740,4.259740,4.259740
942,3.410714,5.000000,3.410714,3.410714,3.410714,3.410714,3.410714,3.410714,3.000000,3.410714,...,3.410714,3.410714,3.410714,3.410714,3.410714,3.410714,3.410714,3.410714,3.410714,3.410714

In [4]:
from sklearn.metrics.pairwise import cosine_similarity  

user_cosine_sim = pd.DataFrame(cosine_similarity(df))
user_cosine_sim

,0,1,2,3,4,5,6,7,8,9,...,933,934,935,936,937,938,939,940,941,942
0,1.000000,0.989116,0.987292,0.990088,0.981615,0.986645,0.983802,0.989893,0.989931,0.989142,...,0.986985,0.989406,0.988325,0.989085,0.986620,0.989974,0.988193,0.989981,0.989286,0.984017
1,0.989116,1.000000,0.995620,0.998250,0.987340,0.994018,0.990664,0.996909,0.998321,0.997773,...,0.995101,0.997976,0.996026,0.997823,0.994440,0.997999,0.995934,0.998253,0.997875,0.992073
2,0.987292,0.995620,1.000000,0.996555,0.985657,0.991778,0.988612,0.995316,0.996658,0.996009,...,0.993453,0.996422,0.994152,0.995848,0.992251,0.996317,0.994127,0.996738,0.996215,0.990247
3,0.990088,0.998250,0.996555,1.000000,0.988174,0.994484,0.991048,0.998039,0.999402,0.998625,...,0.996168,0.999135,0.996850,0.998321,0.995142,0.999037,0.997493,0.999542,0.999020,0.992876
4,0.981615,0.987340,0.985657,0.988174,1.000000,0.984000,0.981335,0.987902,0.988186,0.987505,...,0.985837,0.987533,0.985964,0.987451,0.985246,0.988105,0.986091,0.988276,0.987971,0.983507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.989974,0.997999,0.996317,0.999037,0.988105,0.994102,0.990868,0.997541,0.999064,0.998320,...,0.995914,0.998781,0.996756,0.997956,0.994788,1.000000,0.996675,0.999011,0.998577,0.992601
939,0.988193,0.995934,0.994127,0.997493,0.986091,0.992117,0.988806,0.995778,0.996990,0.996383,...,0.993565,0.996858,0.994170,0.995837,0.992841,0.996675,1.000000,0.997160,0.996513,0.991094
940,0.989981,0.998253,0.996738,0.999542,0.988276,0.994607,0.991141,0.997916,0.999412,0.998665,...,0.996090,0.999101,0.997006,0.998504,0.994849,0.999011,0.997160,1.000000,0.998930,0.992926
941,0.989286,0.997875,0.996215,0.999020,0.987971,0.994302,0.991251,0.997472,0.998982,0.998318,...,0.996091,0.998653,0.996461,0.998017,0.994677,0.998577,0.996513,0.998930,1.000000,0.992680
942,0.984017,0.992073,0.990247,0.992876,0.983507,0.988338,0.986444,0.991682,0.993031,0.992440,...,0.989926,0.992723,0.990340,0.991717,0.989511,0.992601,0.991094,0.992926,0.992680,1.000000

In [5]:
user_mean = df.mean(axis=1)
item_mean = df.mean(axis=0)
user_cosine_sum = user_cosine_sim.sum()

In [6]:
def user_score_function(user, item):
    numerator = 0
    
    for v in range(943):
        numerator += (df[item][v]-user_mean[v])*(user_cosine_sim[user][v])
        score = user_mean[user] + numerator/user_cosine_sum[user]
    
    return score

In [7]:
user_score_function(316, 'Toy Story (1995)')

3.71484789720662

In [8]:
Movie = df.columns
Movie

Index(['Toy Story (1995)', 'GoldenEye (1995)', 'Four Rooms (1995)',
       'Get Shorty (1995)', 'Copycat (1995)',
       'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)',
       'Twelve Monkeys (1995)', 'Babe (1995)', 'Dead Man Walking (1995)',
       'Richard III (1995)',
       ...
       'Kika (1993)', 'Mirage (1995)', 'Mamma Roma (1962)',
       'Sunchaser, The (1996)', 'War at Home, The (1996)',
       'Sweet Nothing (1995)', 'Mat' i syn (1997)', 'B. Monkey (1998)',
       'You So Crazy (1994)', 'Scream of Stone (Schrei aus Stein) (1991)'],
      dtype='object', length=1664)

In [9]:
#user316의 user_score_function 결과
import time
t0 = time.time()
user_316 = []

for item in Movie:
    user_316.append(user_score_function(316, item))
        
user_316 = pd.DataFrame(user_316, index = Movie)
print("소요시간: {:.3f} sec".format(time.time()-t0))

소요시간: 163.262 sec

시간이 오래 걸리는 것 같아서 한번 측정해봤는데 정말 오래걸리네요ㅠㅠ

In [10]:
user_316

                                                  0
Toy Story (1995)                           3.714848
GoldenEye (1995)                           3.536460
Four Rooms (1995)                          3.532881
Get Shorty (1995)                          3.564572
Copycat (1995)                             3.552668
...                                             ...
Sweet Nothing (1995)                       3.571203
Mat' i syn (1997)                          3.569148
B. Monkey (1998)                           3.571263
You So Crazy (1994)                        3.571449
Scream of Stone (Schrei aus Stein) (1991)  3.571047

[1664 rows x 1 columns]

In [11]:
user_316.columns = ['score']
user_316

                                              score
Toy Story (1995)                           3.714848
GoldenEye (1995)                           3.536460
Four Rooms (1995)                          3.532881
Get Shorty (1995)                          3.564572
Copycat (1995)                             3.552668
...                                             ...
Sweet Nothing (1995)                       3.571203
Mat' i syn (1997)                          3.569148
B. Monkey (1998)                           3.571263
You So Crazy (1994)                        3.571449
Scream of Stone (Schrei aus Stein) (1991)  3.571047

[1664 rows x 1 columns]

In [12]:
user_316.sort_values(by='score', ascending=False)

                                     score
Star Wars (1977)                  4.033621
Godfather, The (1972)             3.871143
Fargo (1996)                      3.870110
Raiders of the Lost Ark (1981)    3.852362
Silence of the Lambs, The (1991)  3.844093
...                                    ...
Evita (1996)                      3.435301
Jungle2Jungle (1997)              3.430941
Mars Attacks! (1996)              3.418272
Volcano (1997)                    3.413595
Liar Liar (1997)                  3.381415

[1664 rows x 1 columns]

In [13]:
user_final = user_316.sort_values(by='score', ascending=False)[0:30]

In [14]:
#최종 추천
user_final

                                           score
Star Wars (1977)                        4.033621
Godfather, The (1972)                   3.871143
Fargo (1996)                            3.870110
Raiders of the Lost Ark (1981)          3.852362
Silence of the Lambs, The (1991)        3.844093
Titanic (1997)                          3.833412
Schindler's List (1993)                 3.832686
Shawshank Redemption, The (1994)        3.818123
Empire Strikes Back, The (1980)         3.800607
Return of the Jedi (1983)               3.799069
Usual Suspects, The (1995)              3.789977
L.A. Confidential (1997)                3.778086
Casablanca (1942)                       3.775146
Pulp Fiction (1994)                     3.759934
Princess Bride, The (1987)              3.757224
One Flew Over the Cuckoo's Nest (1975)  3.752116
Braveheart (1995)                       3.743479
Good Will Hunting (1997)                3.731207
Amadeus (1984)                          3.730202
Blade Runner (1982)                     3.729332
Fugitive, The (1993)                    3.726478
Rear Window (1954)                      3.725535
Monty Python and the Holy Grail (1974)  3.724519
Contact (1997)                          3.717385
Toy Story (1995)                        3.714848
To Kill a Mockingbird (1962)            3.713998
Alien (1979)                            3.709470
Boot, Das (1981)                        3.707405
Terminator 2: Judgment Day (1991)       3.705363
Full Monty, The (1997)                  3.699946

### Item based CF

In [90]:
df2 = pd.read_csv('MovieLense.csv')
df2 = df2.T

#drop을 하면 차원이 너무 작아지기 때문에 0.5로 채운다.
df2=df2.fillna(0.5)

In [91]:
item_cosine_sim = pd.DataFrame(cosine_similarity(df2))
item_cosine_sim

,0,1,2,3,4,5,6,7,8,9,...,1654,1655,1656,1657,1658,1659,1660,1661,1662,1663
0,1.000000,0.612886,0.594498,0.608451,0.567354,0.563011,0.705538,0.616878,0.614805,0.525271,...,0.754432,0.753062,0.738268,0.748387,0.755781,0.753062,0.760179,0.748387,0.754932,0.754932
1,0.612886,1.000000,0.540161,0.658528,0.567316,0.494607,0.590914,0.540562,0.490262,0.450328,...,0.656026,0.648089,0.639778,0.648089,0.654029,0.648089,0.657369,0.648089,0.657867,0.657867
2,0.594498,0.540161,1.000000,0.559106,0.516283,0.517452,0.614974,0.466994,0.530533,0.456146,...,0.657779,0.655628,0.647361,0.655628,0.661493,0.657963,0.664726,0.655628,0.655628,0.667302
3,0.608451,0.658528,0.559106,1.000000,0.562461,0.489821,0.631086,0.625416,0.576008,0.489721,...,0.653998,0.647662,0.639160,0.660773,0.661747,0.652032,0.657340,0.647662,0.654946,0.657859
4,0.567354,0.567316,0.516283,0.562461,1.000000,0.479110,0.585898,0.508452,0.528764,0.391234,...,0.654500,0.652369,0.644126,0.652369,0.658222,0.652369,0.661455,0.652369,0.652369,0.663774
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1659,0.753062,0.648089,0.657963,0.652032,0.652369,0.720663,0.726404,0.646518,0.682115,0.613936,...,0.977963,0.974438,0.962797,0.974438,0.982490,1.000000,0.986623,0.974438,0.974438,0.974438
1660,0.760179,0.657369,0.664726,0.657340,0.661455,0.730105,0.730517,0.644600,0.682318,0.622613,...,0.990197,0.986623,0.974846,0.986623,0.994768,0.986623,1.000000,0.991821,0.986623,0.986623
1661,0.748387,0.648089,0.655628,0.647662,0.652369,0.720663,0.719280,0.634991,0.671964,0.613936,...,0.977963,0.974438,0.962797,0.974438,0.982490,0.974438,0.991821,1.000000,0.974438,0.974438
1662,0.754932,0.657867,0.655628,0.654946,0.652369,0.720663,0.726404,0.646518,0.679859,0.613936,...,0.993340,0.974438,0.962797,0.974438,0.982490,0.974438,0.986623,0.974438,1.000000,0.974438
1663,0.754932,0.657867,0.667302,0.657859,0.663774,0.720663,0.726404,0.634991,0.682115,0.613936,...,0.977963,0.974438,0.962797,0.974438,0.982490,0.974438,0.986623,0.974438,0.974438,1.000000

In [92]:
(item_cosine_sim < 0).values.any()
#코사인 유사도의 모든 값이 양수이기 때문에 score function의 분자를 계산할 때 별다른 변환을 하지 않아도 된다.

False

In [93]:
item_mean2 = df2.mean(axis=1)
user_mean2 = df2.mean(axis=0)
item_cosine_sum = item_cosine_sim.sum()

In [94]:
movie_list = Movie.tolist()
movie_list

['Toy Story (1995)',
 'GoldenEye (1995)',
 'Four Rooms (1995)',
 'Get Shorty (1995)',
 'Copycat (1995)',
 'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)',
 'Twelve Monkeys (1995)',
 'Babe (1995)',
 'Dead Man Walking (1995)',
 'Richard III (1995)',
 'Seven (Se7en) (1995)',
 'Usual Suspects, The (1995)',
 'Mighty Aphrodite (1995)',
 'Postino, Il (1994)',
 "Mr. Holland's Opus (1995)",
 'French Twist (Gazon maudit) (1995)',
 'From Dusk Till Dawn (1996)',
 'White Balloon, The (1995)',
 "Antonia's Line (1995)",
 'Angels and Insects (1995)',
 'Muppet Treasure Island (1996)',
 'Braveheart (1995)',
 'Taxi Driver (1976)',
 'Rumble in the Bronx (1995)',
 'Birdcage, The (1996)',
 'Brothers McMullen, The (1995)',
 'Bad Boys (1995)',
 'Apollo 13 (1995)',
 'Batman Forever (1995)',
 'Belle de jour (1967)',
 'Crimson Tide (1995)',
 'Crumb (1994)',
 'Desperado (1995)',
 'Doom Generation, The (1995)',
 'Free Willy 2: The Adventure Home (1995)',
 'Mad Love (1995)',
 'Nadja (1994)',
 'Net, The (1995)',
 'Strange Days (1995)',
 'To Wong Foo, Thanks for Everything! Julie Newmar (1995)',
 'Billy Madison (1995)',
 'Clerks (1994)',
 'Disclosure (1994)',
 'Dolores Claiborne (1994)',
 'Eat Drink Man Woman (1994)',
 'Exotica (1994)',
 'Ed Wood (1994)',
 'Hoop Dreams (1994)',
 'I.Q. (1994)',
 'Star Wars (1977)',
 'Legends of the Fall (1994)',
 'Madness of King George, The (1994)',
 'Natural Born Killers (1994)',
 'Outbreak (1995)',
 'Professional, The (1994)',
 'Pulp Fiction (1994)',
 'Priest (1994)',
 'Quiz Show (1994)',
 'Three Colors: Red (1994)',
 'Three Colors: Blue (1993)',
 'Three Colors: White (1994)',
 'Stargate (1994)',
 'Santa Clause, The (1994)',
 'Shawshank Redemption, The (1994)',
 "What's Eating Gilbert Grape (1993)",
 'While You Were Sleeping (1995)',
 'Ace Ventura: Pet Detective (1994)',
 'Crow, The (1994)',
 'Forrest Gump (1994)',
 'Four Weddings and a Funeral (1994)',
 'Lion King, The (1994)',
 'Mask, The (1994)',
 'Maverick (1994)',
 'Faster Pussycat! Kill! Kill! (1965)',
 'Brother Minister: The Assassination of Malcolm X (1994)',
 "Carlito's Way (1993)",
 'Firm, The (1993)',
 'Free Willy (1993)',
 'Fugitive, The (1993)',
 'Hot Shots! Part Deux (1993)',
 'Hudsucker Proxy, The (1994)',
 'Jurassic Park (1993)',
 'Much Ado About Nothing (1993)',
 "Robert A. Heinlein's The Puppet Masters (1994)",
 'Ref, The (1994)',
 'Remains of the Day, The (1993)',
 'Searching for Bobby Fischer (1993)',
 'Sleepless in Seattle (1993)',
 'Blade Runner (1982)',
 'So I Married an Axe Murderer (1993)',
 'Nightmare Before Christmas, The (1993)',
 'True Romance (1993)',
 'Welcome to the Dollhouse (1995)',
 'Home Alone (1990)',
 'Aladdin (1992)',
 'Terminator 2: Judgment Day (1991)',
 'Dances with Wolves (1990)',
 'Silence of the Lambs, The (1991)',
 'Snow White and the Seven Dwarfs (1937)',
 'Fargo (1996)',
 'Heavy Metal (1981)',
 'Aristocats, The (1970)',
 'All Dogs Go to Heaven 2 (1996)',
 'Theodore Rex (1995)',
 'Sgt. Bilko (1996)',
 'Diabolique (1996)',
 'Moll Flanders (1996)',
 'Kids in the Hall: Brain Candy (1996)',
 'Mystery Science Theater 3000: The Movie (1996)',
 'Operation Dumbo Drop (1995)',
 'Truth About Cats & Dogs, The (1996)',
 'Flipper (1996)',
 'Horseman on the Roof, The (Hussard sur le toit, Le) (1995)',
 'Wallace & Gromit: The Best of Aardman Animation (1996)',
 'Haunted World of Edward D. Wood Jr., The (1995)',
 'Cold Comfort Farm (1995)',
 'Rock, The (1996)',
 'Twister (1996)',
 'Maya Lin: A Strong Clear Vision (1994)',
 'Striptease (1996)',
 'Independence Day (ID4) (1996)',
 'Cable Guy, The (1996)',
 'Frighteners, The (1996)',
 'Lone Star (1996)',
 'Phenomenon (1996)',
 'Spitfire Grill, The (1996)',
 'Godfather, The (1972)',
 'Supercop (1992)',
 'Bound (1996)',
 'Kansas City (1996)',
 "Breakfast at Tiffany's (1961)",
 'Wizard of Oz, The (1939)',
 'Gone with the Wind (1939)',
 'Citizen Kane (1941)',
 '2001: A Space Odyssey (1968)',
 'Mr. Smith Goes to Washington (1939)',
 'Big Night (1996)',
 'D3: The Mighty Ducks (1996)',
 'Love Bug, The (1969)',
 'Homeward Bound: The Incredible Journey (1993)',
 '20,000 Leagues Under the Sea (1954)',
 'Bedknobs and Broomsticks (1971)',
 'Sound of Music, The (1965)',
 'Die Hard (1988)',
 'Lawnmower Man, The (1992)',
 'Unhook the Stars (1996)',
 'Long Kiss Goodnight, The (1996)',
 'Ghost and the Darkness, The (1996)',
 'Jude (1996)',
 'Swingers (1996)',
 'Willy Wonka and the Chocolate Factory (1971)',
 'Sleeper (1973)',
 'Fish Called Wanda, A (1988)',
 "Monty Python's Life of Brian (1979)",
 'Dirty Dancing (1987)',
 'Reservoir Dogs (1992)',
 'Platoon (1986)',
 "Weekend at Bernie's (1989)",
 'Basic Instinct (1992)',
 'Glengarry Glen Ross (1992)',
 'Top Gun (1986)',
 'On Golden Pond (1981)',
 'Return of the Pink Panther, The (1974)',
 'Abyss, The (1989)',
 'Jean de Florette (1986)',
 'Manon of the Spring (Manon des sources) (1986)',
 'Private Benjamin (1980)',
 'Monty Python and the Holy Grail (1974)',
 'Wrong Trousers, The (1993)',
 'Cinema Paradiso (1988)',
 'Delicatessen (1991)',
 'Empire Strikes Back, The (1980)',
 'Princess Bride, The (1987)',
 'Raiders of the Lost Ark (1981)',
 'Brazil (1985)',
 'Aliens (1986)',
 'Good, The Bad and The Ugly, The (1966)',
 '12 Angry Men (1957)',
 'Clockwork Orange, A (1971)',
 'Apocalypse Now (1979)',
 'Return of the Jedi (1983)',
 'GoodFellas (1990)',
 'Alien (1979)',
 'Army of Darkness (1993)',
 'Psycho (1960)',
 'Blues Brothers, The (1980)',
 'Godfather: Part II, The (1974)',
 'Full Metal Jacket (1987)',
 'Grand Day Out, A (1992)',
 'Henry V (1989)',
 'Amadeus (1984)',
 'Raging Bull (1980)',
 'Right Stuff, The (1983)',
 'Sting, The (1973)',
 'Terminator, The (1984)',
 'Dead Poets Society (1989)',
 'Graduate, The (1967)',
 'Nikita (La Femme Nikita) (1990)',
 'Bridge on the River Kwai, The (1957)',
 'Shining, The (1980)',
 'Evil Dead II (1987)',
 'Groundhog Day (1993)',
 'Unforgiven (1992)',
 'Back to the Future (1985)',
 'Patton (1970)',
 'Akira (1988)',
 'Cyrano de Bergerac (1990)',
 'Young Frankenstein (1974)',
 'This Is Spinal Tap (1984)',
 'Indiana Jones and the Last Crusade (1989)',
 'M*A*S*H (1970)',
 'Unbearable Lightness of Being, The (1988)',
 'Room with a View, A (1986)',
 'Pink Floyd - The Wall (1982)',
 'Field of Dreams (1989)',
 'When Harry Met Sally... (1989)',
 "Bram Stoker's Dracula (1992)",
 'Cape Fear (1991)',
 'Nightmare on Elm Street, A (1984)',
 'Mirror Has Two Faces, The (1996)',
 'Breaking the Waves (1996)',
 'Star Trek: First Contact (1996)',
 'Sling Blade (1996)',
 'Ridicule (1996)',
 '101 Dalmatians (1996)',
 'Die Hard 2 (1990)',
 'Star Trek VI: The Undiscovered Country (1991)',
 'Star Trek: The Wrath of Khan (1982)',
 'Star Trek III: The Search for Spock (1984)',
 'Star Trek IV: The Voyage Home (1986)',
 'Batman Returns (1992)',
 'Young Guns (1988)',
 'Under Siege (1992)',
 'Jaws (1975)',
 'Mars Attacks! (1996)',
 'Citizen Ruth (1996)',
 'Jerry Maguire (1996)',
 'Raising Arizona (1987)',
 'Sneakers (1992)',
 'Beavis and Butt-head Do America (1996)',
 'Last of the Mohicans, The (1992)',
 'Kolya (1996)',
 'Jungle2Jungle (1997)',
 "Smilla's Sense of Snow (1997)",
 "Devil's Own, The (1997)",
 'Chasing Amy (1997)',
 'Turbo: A Power Rangers Movie (1997)',
 'Grosse Pointe Blank (1997)',
 'Austin Powers: International Man of Mystery (1997)',
 'Fifth Element, The (1997)',
 'Shall We Dance? (1996)',
 'Lost World: Jurassic Park, The (1997)',
 'Pillow Book, The (1995)',
 'Batman & Robin (1997)',
 "My Best Friend's Wedding (1997)",
 'When the Cats Away (Chacun cherche son chat) (1996)',
 'Men in Black (1997)',
 'Contact (1997)',
 'George of the Jungle (1997)',
 'Event Horizon (1997)',
 'Air Bud (1997)',
 'In the Company of Men (1997)',
 'Steel (1997)',
 'Mimic (1997)',
 'Hunt for Red October, The (1990)',
 'Kull the Conqueror (1997)',
 'unknown',
 'Full Monty, The (1997)',
 'Gattaca (1997)',
 'Starship Troopers (1997)',
 'Good Will Hunting (1997)',
 'Heat (1995)',
 'Sabrina (1995)',
 'Sense and Sensibility (1995)',
 'Leaving Las Vegas (1995)',
 'Restoration (1995)',
 'Bed of Roses (1996)',
 'Once Upon a Time... When We Were Colored (1995)',
 'Up Close and Personal (1996)',
 'River Wild, The (1994)',
 'Time to Kill, A (1996)',
 'Emma (1996)',
 'Tin Cup (1996)',
 'Secrets & Lies (1996)',
 'English Patient, The (1996)',
 "Marvin's Room (1996)",
 'Scream (1996)',
 'Evita (1996)',
 'Fierce Creatures (1997)',
 'Absolute Power (1997)',
 'Rosewood (1997)',
 'Donnie Brasco (1997)',
 'Liar Liar (1997)',
 'Breakdown (1997)',
 'Promesse, La (1996)',
 "Ulee's Gold (1997)",
 'Face/Off (1997)',
 'Hoodlum (1997)',
 'Air Force One (1997)',
 'In & Out (1997)',
 'L.A. Confidential (1997)',
 'Fly Away Home (1996)',
 'Ice Storm, The (1997)',
 'Mrs. Brown (Her Majesty, Mrs. Brown) (1997)',
 "Devil's Advocate, The (1997)",
 'FairyTale: A True Story (1997)',
 'Deceiver (1997)',
 'Rainmaker, The (1997)',
 'Wings of the Dove, The (1997)',
 'Midnight in the Garden of Good and Evil (1997)',
 'Titanic (1997)',
 '3 Ninjas: High Noon At Mega Mountain (1998)',
 'Apt Pupil (1998)',
 'As Good As It Gets (1997)',
 'In the Name of the Father (1993)',
 "Schindler's List (1993)",
 'Everyone Says I Love You (1996)',
 'Paradise Lost: The Child Murders at Robin Hood Hills (1996)',
 'Mother (1996)',
 'Murder at 1600 (1997)',
 "Dante's Peak (1997)",
 'Lost Highway (1997)',
 'Crash (1996)',
 'G.I. Jane (1997)',
 'Cop Land (1997)',
 'Conspiracy Theory (1997)',
 'Desperate Measures (1998)',
 '187 (1997)',
 'Edge, The (1997)',
 'Kiss the Girls (1997)',
 'Game, The (1997)',
 'U Turn (1997)',
 'How to Be a Player (1997)',
 'Playing God (1997)',
 'House of Yes, The (1997)',
 'Bean (1997)',
 'Mad City (1997)',
 'Boogie Nights (1997)',
 'Critical Care (1997)',
 'Man Who Knew Too Little, The (1997)',
 'Alien: Resurrection (1997)',
 'Apostle, The (1997)',
 'Deconstructing Harry (1997)',
 'Jackie Brown (1997)',
 'Wag the Dog (1997)',
 'Hard Rain (1998)',
 'Fallen (1998)',
 'Prophecy II, The (1998)',
 'Spice World (1997)',
 'Deep Rising (1998)',
 'Wedding Singer, The (1998)',
 'Sphere (1998)',
 'Client, The (1994)',
 "One Flew Over the Cuckoo's Nest (1975)",
 'Spawn (1997)',
 'Assignment, The (1997)',
 'Wonderland (1997)',
 'Incognito (1997)',
 'Blues Brothers 2000 (1998)',
 'Sudden Death (1995)',
 'Ace Ventura: When Nature Calls (1995)',
 'Powder (1995)',
 'Dangerous Minds (1995)',
 'Clueless (1995)',
 'Bio-Dome (1996)',
 'Black Sheep (1996)',
 'Mary Reilly (1996)',
 'Bridges of Madison County, The (1995)',
 'Jeffrey (1995)',
 'Judge Dredd (1995)',
 'Mighty Morphin Power Rangers: The Movie (1995)',
 'Showgirls (1995)',
 'Houseguest (1994)',
 'Heavyweights (1994)',
 'Miracle on 34th Street (1994)',
 'Tales From the Crypt Presents: Demon Knight (1995)',
 'Star Trek: Generations (1994)',
 "Muriel's Wedding (1994)",
 'Adventures of Priscilla, Queen of the Desert, The (1994)',
 'Flintstones, The (1994)',
 'Naked Gun 33 1/3: The Final Insult (1994)',
 'True Lies (1994)',
 'Addams Family Values (1993)',
 'Age of Innocence, The (1993)',
 'Beverly Hills Cop III (1994)',
 'Black Beauty (1994)',
 'Fear of a Black Hat (1993)',
 'Last Action Hero (1993)',
 'Man Without a Face, The (1993)',
 'Mrs. Doubtfire (1993)',
 'Radioland Murders (1994)',
 'Robin Hood: Men in Tights (1993)',
 'Serial Mom (1994)',
 'Striking Distance (1993)',
 'Super Mario Bros. (1993)',
 'Three Musketeers, The (1993)',
 'Little Rascals, The (1994)',
 'Brady Bunch Movie, The (1995)',
 'Ghost (1990)',
 'Batman (1989)',
 'Pinocchio (1940)',
 'Mission: Impossible (1996)',
 'Thinner (1996)',
 'Spy Hard (1996)',
 'Close Shave, A (1995)',
 'Jack (1996)',
 'Kingpin (1996)',
 'Nutty Professor, The (1996)',
 'Very Brady Sequel, A (1996)',
 'Tales from the Crypt Presents: Bordello of Blood (1996)',
 'My Favorite Year (1982)',
 'Apple Dumpling Gang, The (1975)',
 'Old Yeller (1957)',
 'Parent Trap, The (1961)',
 'Cinderella (1950)',
 'Mary Poppins (1964)',
 'Alice in Wonderland (1951)',
 "William Shakespeare's Romeo and Juliet (1996)",
 'Aladdin and the King of Thieves (1996)',
 'E.T. the Extra-Terrestrial (1982)',
 'Children of the Corn: The Gathering (1996)',
 'Bob Roberts (1992)',
 'Transformers: The Movie, The (1986)',
 'To Kill a Mockingbird (1962)',
 'Harold and Maude (1971)',
 'Day the Earth Stood Still, The (1951)',
 'Duck Soup (1933)',
 'Highlander (1986)',
 'Fantasia (1940)',
 'Heathers (1989)',
 'Forbidden Planet (1956)',
 'Butch Cassidy and the Sundance Kid (1969)',
 'American Werewolf in London, An (1981)',
 "Amityville 1992: It's About Time (1992)",
 'Amityville 3-D (1983)',
 'Amityville: A New Generation (1993)',
 'Amityville II: The Possession (1982)',
 'Amityville Horror, The (1979)',
 'Amityville Curse, The (1990)',
 'Birds, The (1963)',
 'Blob, The (1958)',
 'Body Snatcher, The (1945)',
 'Burnt Offerings (1976)',
 'Carrie (1976)',
 'Omen, The (1976)',
 'Star Trek: The Motion Picture (1979)',
 'Star Trek V: The Final Frontier (1989)',
 'Grease (1978)',
 'Jaws 2 (1978)',
 'Jaws 3-D (1983)',
 'Bastard Out of Carolina (1996)',
 "Jackie Chan's First Strike (1996)",
 'Beverly Hills Ninja (1997)',
 'Free Willy 3: The Rescue (1997)',
 'Nixon (1995)',
 'Cry, the Beloved Country (1995)',
 'Crossing Guard, The (1995)',
 'Smoke (1995)',
 'Like Water For Chocolate (Como agua para chocolate) (1992)',
 'Secret of Roan Inish, The (1994)',
 'Vanya on 42nd Street (1994)',
 'Jungle Book, The (1994)',
 'Red Rock West (1992)',
 'Bronx Tale, A (1993)',
 'Rudy (1993)',
 'Short Cuts (1993)',
 'Tombstone (1993)',
 'Courage Under Fire (1996)',
 'Dragonheart (1996)',
 'James and the Giant Peach (1996)',
 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1963)',
 'Trainspotting (1996)',
 'First Wives Club, The (1996)',
 'Matilda (1996)',
 'Philadelphia Story, The (1940)',
 'Vertigo (1958)',
 'North by Northwest (1959)',
 'Apartment, The (1960)',
 'Some Like It Hot (1959)',
 'Casablanca (1942)',
 'Maltese Falcon, The (1941)',
 'My Fair Lady (1964)',
 'Sabrina (1954)',
 'Roman Holiday (1953)',
 'Sunset Blvd. (1950)',
 'Notorious (1946)',
 'To Catch a Thief (1955)',
 'Adventures of Robin Hood, The (1938)',
 'East of Eden (1955)',
 'Thin Man, The (1934)',
 'His Girl Friday (1940)',
 'Around the World in 80 Days (1956)',
 "It's a Wonderful Life (1946)",
 'Bringing Up Baby (1938)',
 'African Queen, The (1951)',
 'Cat on a Hot Tin Roof (1958)',
 'Dumbo (1941)',
 'Bananas (1971)',
 'Candidate, The (1972)',
 'Bonnie and Clyde (1967)',
 'Dial M for Murder (1954)',
 'Rebel Without a Cause (1955)',
 'Streetcar Named Desire, A (1951)',
 'People vs. Larry Flynt, The (1996)',
 'My Left Foot (1989)',
 'Magnificent Seven, The (1954)',
 'Lawrence of Arabia (1962)',
 'Wings of Desire (1987)',
 'Third Man, The (1949)',
 'Annie Hall (1977)',
 'Boot, Das (1981)',
 'Local Hero (1983)',
 'Manhattan (1979)',
 "Miller's Crossing (1990)",
 'Treasure of the Sierra Madre, The (1948)',
 'Great Escape, The (1963)',
 'Deer Hunter, The (1978)',
 'Down by Law (1986)',
 'Cool Hand Luke (1967)',
 'Great Dictator, The (1940)',
 'Big Sleep, The (1946)',
 'Ben-Hur (1959)',
 'Gandhi (1982)',
 'Killing Fields, The (1984)',
 'My Life as a Dog (Mitt liv som hund) (1985)',
 'Man Who Would Be King, The (1975)',
 'Shine (1996)',
 'Kama Sutra: A Tale of Love (1996)',
 'Daytrippers, The (1996)',
 'Traveller (1997)',
 'Addicted to Love (1997)',
 'Ponette (1996)',
 'My Own Private Idaho (1991)',
 'Anastasia (1997)',
 'Mouse Hunt (1997)',
 'Money Train (1995)',
 'Mortal Kombat (1995)',
 'Pocahontas (1995)',
 'Miserables, Les (1995)',
 "Things to Do in Denver when You're Dead (1995)",
 'Vampire in Brooklyn (1995)',
 'Broken Arrow (1996)',
 "Young Poisoner's Handbook, The (1995)",
 'NeverEnding Story III, The (1994)',
 'Rob Roy (1995)',
 'Die Hard: With a Vengeance (1995)',
 'Lord of Illusions (1995)',
 'Species (1995)',
 'Walk in the Clouds, A (1995)',
 'Waterworld (1995)',
 "White Man's Burden (1995)",
 'Wild Bill (1995)',
 'Farinelli: il castrato (1994)',
 'Heavenly Creatures (1994)',
 'Interview with the Vampire (1994)',
 "Kid in King Arthur's Court, A (1995)",
 "Mary Shelley's Frankenstein (1994)",
 'Quick and the Dead, The (1995)',
 "Stephen King's The Langoliers (1995)",
 'Tales from the Hood (1995)',
 'Village of the Damned (1995)',
 'Clear and Present Danger (1994)',
 "Wes Craven's New Nightmare (1994)",
 'Speed (1994)',
 'Wolf (1994)',
 'Wyatt Earp (1994)',
 'Another Stakeout (1993)',
 'Blown Away (1994)',
 'Body Snatchers (1993)',
 'Boxing Helena (1993)',
 "City Slickers II: The Legend of Curly's Gold (1994)",
 'Cliffhanger (1993)',
 'Coneheads (1993)',
 'Demolition Man (1993)',
 'Fatal Instinct (1993)',
 'Englishman Who Went Up a Hill, But Came Down a Mountain, The (1995)',
 'Kalifornia (1993)',
 'Piano, The (1993)',
 'Romeo Is Bleeding (1993)',
 'Secret Garden, The (1993)',
 'Son in Law (1993)',
 'Terminal Velocity (1994)',
 'Hour of the Pig, The (1993)',
 'Beauty and the Beast (1991)',
 'Wild Bunch, The (1969)',
 'Hellraiser: Bloodline (1996)',
 'Primal Fear (1996)',
 'True Crime (1995)',
 'Stalingrad (1993)',
 'Heavy (1995)',
 'Fan, The (1996)',
 'Hunchback of Notre Dame, The (1996)',
 'Eraser (1996)',
 'Big Squeeze, The (1996)',
 'Police Story 4: Project S (Chao ji ji hua) (1993)',
 "Daniel Defoe's Robinson Crusoe (1996)",
 'For Whom the Bell Tolls (1943)',
 'American in Paris, An (1951)',
 'Rear Window (1954)',
 'It Happened One Night (1934)',
 'Meet Me in St. Louis (1944)',
 'All About Eve (1950)',
 'Rebecca (1940)',
 'Spellbound (1945)',
 'Father of the Bride (1950)',
 'Gigi (1958)',
 'Laura (1944)',
 'Lost Horizon (1937)',
 'My Man Godfrey (1936)',
 'Giant (1956)',
 '39 Steps, The (1935)',
 'Night of the Living Dead (1968)',
 'Blue Angel, The (Blaue Engel, Der) (1930)',
 'Picnic (1955)',
 'Extreme Measures (1996)',
 'Chamber, The (1996)',
 'Davy Crockett, King of the Wild Frontier (1955)',
 'Swiss Family Robinson (1960)',
 'Angels in the Outfield (1994)',
 'Three Caballeros, The (1945)',
 'Sword in the Stone, The (1963)',
 'So Dear to My Heart (1949)',
 'Robin Hood: Prince of Thieves (1991)',
 'Sleepers (1996)',
 'Victor/Victoria (1982)',
 'Great Race, The (1965)',
 'Crying Game, The (1992)',
 "Sophie's Choice (1982)",
 'Christmas Carol, A (1938)',
 "Microcosmos: Le peuple de l'herbe (1996)",
 'Fog, The (1980)',
 'Escape from New York (1981)',
 'Howling, The (1981)',
 'Return of Martin Guerre, The (Retour de Martin Guerre, Le) (1982)',
 'Tin Drum, The (Blechtrommel, Die) (1979)',
 'Cook the Thief His Wife & Her Lover, The (1989)',
 'Paths of Glory (1957)',
 'Grifters, The (1990)',
 'The Innocent (1994)',
 'Thin Blue Line, The (1988)',
 'Paris Is Burning (1990)',
 'Once Upon a Time in the West (1969)',
 'Ran (1985)',
 'Quiet Man, The (1952)',
 'Once Upon a Time in America (1984)',
 'Seventh Seal, The (Sjunde inseglet, Det) (1957)',
 'Glory (1989)',
 'Rosencrantz and Guildenstern Are Dead (1990)',
 'Touch of Evil (1958)',
 'Chinatown (1974)',
 'Stand by Me (1986)',
 'M (1931)',
 'Manchurian Candidate, The (1962)',
 'Pump Up the Volume (1990)',
 'Arsenic and Old Lace (1944)',
 'Fried Green Tomatoes (1991)',
 'High Noon (1952)',
 'Somewhere in Time (1980)',
 'Being There (1979)',
 'Paris, Texas (1984)',
 'Alien 3 (1992)',
 "Blood For Dracula (Andy Warhol's Dracula) (1974)",
 'Audrey Rose (1977)',
 'Blood Beach (1981)',
 'Body Parts (1991)',
 'Bride of Frankenstein (1935)',
 'Candyman (1992)',
 'Cape Fear (1962)',
 'Cat People (1982)',
 'Nosferatu (Nosferatu, eine Symphonie des Grauens) (1922)',
 'Crucible, The (1996)',
 'Fire on the Mountain (1996)',
 'Volcano (1997)',
 'Conan the Barbarian (1981)',
 'Wishmaster (1997)',
 'I Know What You Did Last Summer (1997)',
 'Rocket Man (1997)',
 'In the Line of Fire (1993)',
 'Executive Decision (1996)',
 'Perfect World, A (1993)',
 "McHale's Navy (1997)",
 'Leave It to Beaver (1997)',
 'Jackal, The (1997)',
 'Seven Years in Tibet (1997)',
 'Dark City (1998)',
 'American President, The (1995)',
 'Casino (1995)',
 'Persuasion (1995)',
 'Kicking and Screaming (1995)',
 'City Hall (1996)',
 'Basketball Diaries, The (1995)',

In [95]:
def item_score_function(item, user):
    numerator = 0
    for j in range(1664):
        numerator += (item_cosine_sim[j][movie_list.index(item)])*(df2[user][j]-item_mean2[j])
        score = item_mean2[item] + numerator/item_cosine_sum[movie_list.index(item)]
    
    return score

In [96]:
item_score_function('Toy Story (1995)', 316)

1.9727955827847659

In [97]:
item_score_function('GoldenEye (1995)', 316)

0.7253806472528159

In [98]:
#user316의 item_score_function 결과
t0 = time.time()
item_316 = []

for item in Movie:
    item_316.append(item_score_function(item, 316))
        
item_316 = pd.DataFrame(item_316, index=Movie)
print("소요시간: {:.3f} sec".format(time.time()-t0))

소요시간: 359.877 sec

이번에는 더 오래 걸려요ㅠㅠ

In [99]:
item_316

                                                  0
Toy Story (1995)                           1.972796
GoldenEye (1995)                           0.725381
Four Rooms (1995)                          0.599928
Get Shorty (1995)                          1.018646
Copycat (1995)                             0.612919
...                                             ...
Sweet Nothing (1995)                       0.372457
Mat' i syn (1997)                          0.370678
B. Monkey (1998)                           0.373134
You So Crazy (1994)                        0.372261
Scream of Stone (Schrei aus Stein) (1991)  0.372233

[1664 rows x 1 columns]

In [100]:
item_316.columns = ['score']
item_316.sort_values(by='score', ascending=False)

                                                      score
Star Wars (1977)                                   2.738959
Fargo (1996)                                       2.323799
Return of the Jedi (1983)                          2.238955
Contact (1997)                                     2.153177
Raiders of the Lost Ark (1981)                     2.014806
...                                                     ...
Power 98 (1995)                                    0.370520
Bloody Child, The (1996)                           0.370520
Nobody Loves Me (Keiner liebt mich) (1994)         0.370514
Getting Away With Murder (1996)                    0.370475
Police Story 4: Project S (Chao ji ji hua) (1993)  0.370471

[1664 rows x 1 columns]

In [101]:
item_final = item_316.sort_values(by='score', ascending=False)[0:30]

In [102]:
item_final

                                              score
Star Wars (1977)                           2.738959
Fargo (1996)                               2.323799
Return of the Jedi (1983)                  2.238955
Contact (1997)                             2.153177
Raiders of the Lost Ark (1981)             2.014806
Godfather, The (1972)                      2.010345
English Patient, The (1996)                1.981273
Toy Story (1995)                           1.972796
Silence of the Lambs, The (1991)           1.912207
Scream (1996)                              1.863605
Pulp Fiction (1994)                        1.833461
Air Force One (1997)                       1.810892
Empire Strikes Back, The (1980)            1.785227
Titanic (1997)                             1.765001
Liar Liar (1997)                           1.737846
Twelve Monkeys (1995)                      1.724363
Independence Day (ID4) (1996)              1.690434
Jerry Maguire (1996)                       1.664677
Rock, The (1996)                           1.635695
Fugitive, The (1993)                       1.607262
Princess Bride, The (1987)                 1.605445
Schindler's List (1993)                    1.598770
Back to the Future (1985)                  1.579782
Star Trek: First Contact (1996)            1.577792
Indiana Jones and the Last Crusade (1989)  1.547833
Monty Python and the Holy Grail (1974)     1.537188
Shawshank Redemption, The (1994)           1.527425
L.A. Confidential (1997)                   1.525701
Full Monty, The (1997)                     1.515754
Braveheart (1995)                          1.495164

-> item based의 경우 결측치를 어떻게 처리해야 좋을지 감이 잘 안왔다. 각 user의 평균 점수로 채우면 user-based와 같은 결과가 나오고 item의 평균으로 채우면 소수의 사람들이 5.0을 준 영화들이 높은 순위를 받았다. 결측치를 채우거나 제거하는 대신 0.5로 채우면 점수는 낮게 나오지만 이런 영향은 어느정도 줄어들었다!!